# get MathPix API from https://accounts.mathpix.com/account
api:
  api-id: xxxxxxx
  api-key: xxxxxxxxxxxxxxxxx
server:
  port: 8080
  cache-path: ./cache
  pgsql:
    path: localhost
    port: 5432
    db-name: xxx
    username: xxx
    password: xxxxxxxxxx
  jwt:
    signing-key: don't-tell-others
    expires-time: 604800